<?php

/**
 * @file
 * Install, update and uninstall functions for the ckeditor_bs_grid module.
 */

use Drupal\Core\Config\FileStorage;

/**
 * Add the CKEditor BS Grid updated configuration.
 */
function ckeditor_bs_grid_update_8201() {
  // Load the entire install file.
  $config_path = \Drupal::service('extension.list.module')->getPath('ckeditor_bs_grid') . '/config/install';
  $source = new FileStorage($config_path);
  $config_storage = \Drupal::service('config.storage');
  $config_storage->write('ckeditor_bs_grid.settings', $source->read('ckeditor_bs_grid.settings'));
}

/**
 * Rebuild caches to recognize plugin changes.
 */
function ckeditor_bs_grid_update_9001(&$sandbox) {
  // Nothing, just rebuild cache.
}
